In [1]:
import numpy as np

print(np.__version__)


1.26.4


Creattion of Arrays


In [2]:
# 1. From a Python list (most common)
my_list = [1, 2, 3, 4, 5]
arr_1d = np.array(my_list)
print(f"1D Array:\n {arr_1d}")

my_list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(my_list_2d)
print(f"\n2D Array (Matrix):\n {arr_2d}")

# 2. Using built-in creation functions
# 'arange' is like Python's 'range'
arr_range = np.arange(0, 10, 2)  # Start, Stop (exclusive), Step
print(f"\nArray from arange:\n {arr_range}")

# 'zeros' for an array of all zeros
arr_zeros = np.zeros((3, 4)) # Shape is (rows, cols)
print(f"\nZeros array (3x4):\n {arr_zeros}")

# 'ones' for an array of all ones
arr_ones = np.ones((2, 5), dtype=np.int16) # Can specify data type
print(f"\nOnes array (2x5):\n {arr_ones}")

# 'linspace' for evenly spaced numbers
# (Start, Stop (inclusive), Number of points)
arr_linspace = np.linspace(0, 10, 5)
print(f"\nLinspace array:\n {arr_linspace}")

# 3. Creating random data (super useful!)
# Random numbers from 0 to 1 (Uniform distribution)
arr_rand = np.random.rand(3,3)
print(f"\nRandom array (uniform):\n {arr_rand}")

# Random numbers from a "Normal" (Gaussian) distribution
arr_randn = np.random.randn(3, 3)
print(f"\nRandom array (normal):\n {arr_randn}")

# Random integers
# (Low, High (exclusive), Size)
arr_randint = np.random.randint(1, 100, (2, 4))
print(f"\nRandom integer array:\n {arr_randint}")

1D Array:
 [1 2 3 4 5]

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array from arange:
 [0 2 4 6 8]

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (2x5):
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Linspace array:
 [ 0.   2.5  5.   7.5 10. ]

Random array (uniform):
 [[0.29527056 0.97392777 0.48191076]
 [0.36994513 0.43486008 0.59268317]
 [0.52678391 0.21160661 0.03005152]]

Random array (normal):
 [[-0.03536055  0.95196373 -1.33602257]
 [ 0.0062962  -2.3391262   1.56516708]
 [-0.79886948  1.03402174 -1.24088857]]

Random integer array:
 [[90 16  6 41]
 [49 79 30 50]]


Array Attributes

In [3]:
# Let's create a test array
data = np.random.randint(1, 20, (3, 4))
print(f"Our data:\n {data}")

# Get the shape (rows, columns)
print(f"\nShape: {data.shape}")

# Get the number of dimensions
print(f"Dimensions: {data.ndim}")

# Get the total number of elements
print(f"Size: {data.size}")

# Get the data type
print(f"Data Type: {data.dtype}")

Our data:
 [[10 18  3  3]
 [19 15  5 12]
 [ 9 15  3 12]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data Type: int64


1D Array Indexing

In [4]:
a = np.arange(10)
print(f"Array: {a}")

# Get a single element
print(f"Element at index 3: {a[3]}")

# Get a slice
print(f"Elements from index 2 to 5: {a[2:6]}")

# Get all elements from index 4 onwards
print(f"Elements from index 4: {a[4:]}")

# Get elements with a step
print(f"Every other element: {a[::2]}")

# Reverse the array
print(f"Reversed array: {a[::-1]}")

Array: [0 1 2 3 4 5 6 7 8 9]
Element at index 3: 3
Elements from index 2 to 5: [2 3 4 5]
Elements from index 4: [4 5 6 7 8 9]
Every other element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


2D Array Slicing

In [5]:
# Let's build a sample matrix
b = np.random.randint(10, 100, (5, 5))
print(f"Our 2D Array:\n {b}")

# Get a single element (Row 1, Column 2) -> (remember 0-indexing)
print(f"\nElement (1, 2): {b[1, 2]}")

# Get an entire row (Row 0)
print(f"\nRow 0: {b[0, :]}") # ':' means "all"

# Get an entire column (Column 1)
print(f"\nColumn 1: {b[:, 1]}")

# Get a "slice" or sub-matrix
# Get the top-left 2x2 matrix
sub_matrix = b[0:2, 0:2] # Rows 0-1, Columns 0-1
print(f"\nTop-left 2x2:\n {sub_matrix}")

# Get the bottom-right 3x3 matrix
sub_matrix_2 = b[2:, 2:]
print(f"\nBottom-right 3x3:\n {sub_matrix_2}")

Our 2D Array:
 [[28 67 41 25 58]
 [84 29 49 29 87]
 [44 57 77 96 71]
 [78 33 42 82 73]
 [61 93 90 37 86]]

Element (1, 2): 49

Row 0: [28 67 41 25 58]

Column 1: [67 29 57 33 93]

Top-left 2x2:
 [[28 67]
 [84 29]]

Bottom-right 3x3:
 [[77 96 71]
 [42 82 73]
 [90 37 86]]


View vs Copies

In [6]:
# 1. The 'View' (default behavior)
a = np.arange(5)
print(f"Original array: {a}")

# Create a slice (a view)
a_view = a[1:4]
print(f"View: {a_view}")

# Now, modify the view
a_view[0] = 99
print(f"\nModified view: {a_view}")
print(f"!!! Original array is CHANGED: {a}")


print('-------------------------------------')

# 2. How to make a 'Copy'
b = np.arange(5)
print(f"\nOriginal array 'b': {b}")

# Explicitly create a copy
b_copy = b[1:4].copy()
print(f"Copy: {b_copy}")

# Modify the copy
b_copy[0] = 77
print(f"\nModified copy: {b_copy}")
print(f"Original 'b' is UNCHANGED: {b}")

Original array: [0 1 2 3 4]
View: [1 2 3]

Modified view: [99  2  3]
!!! Original array is CHANGED: [ 0 99  2  3  4]
-------------------------------------

Original array 'b': [0 1 2 3 4]
Copy: [1 2 3]

Modified copy: [77  2  3]
Original 'b' is UNCHANGED: [0 1 2 3 4]


Vectorization

In [7]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Python list way (slow)
# c = []
# for i in range(len(a)):
#     c.append(a[i] + b[i])

# NumPy vectorized way (fast)
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a * 10 = {a * 10}")
print(f"a ** 2 = {a ** 2}")
print(f"a > 2 = {a > 2}") # Also works for comparisons!

a + b = [11 22 33]
a * b = [10 40 90]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]
a > 2 = [False False  True]


Universal Functions

In [8]:
data = np.array([1, 4, 9, 16])

# Square root
print(f"sqrt: {np.sqrt(data)}")

# Exponential (e^x)
print(f"exp: {np.exp(data)}")

# Sine/Cosine
print(f"sin: {np.sin(data)}")

# Max (compares two arrays element-wise)
data2 = np.array([5, 2, 10, 15])
print(f"Maximum: {np.maximum(data, data2)}")

sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Maximum: [ 5  4 10 16]


Aggregations and the axis Parameter

In [9]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"Data:\n {data}")

# 1. Aggregate the whole array (no axis)
print(f"\nTotal sum: {data.sum()}")
print(f"Total mean: {data.mean()}")
print(f"Total max: {data.max()}")

# 2. Aggregate along axis=0 (down the columns)
# Result is 1D array (one value per column)
print(f"\nSum of columns (axis=0): {data.sum(axis=0)}")
print(f"Mean of columns (axis=0): {data.mean(axis=0)}")

# 3. Aggregate along axis=1 (across the rows)
# Result is 1D array (one value per row)
print(f"\nSum of rows (axis=1): {data.sum(axis=1)}")
print(f"Max of rows (axis=1): {data.max(axis=1)}")

Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Total sum: 45
Total mean: 5.0
Total max: 9

Sum of columns (axis=0): [12 15 18]
Mean of columns (axis=0): [4. 5. 6.]

Sum of rows (axis=1): [ 6 15 24]
Max of rows (axis=1): [3 6 9]


Broadcasting

In [10]:
# Example 1: Array and a Scalar (Easiest case)
a = np.arange(5)
print(f"Array: {a}")
print(f"Array + 10: {a + 10}") 
# 10 is "broadcast" from shape () to shape (5,)
# Becomes [10, 10, 10, 10, 10]

print('-------------------------')

# Example 2: 2D array (3x3) and 1D array (3,)
matrix = np.ones((3, 3))
row = np.array([1, 2, 3]) # Shape (3,)
print(f"\nMatrix (3x3):\n {matrix}")
print(f"Row (3,):\n {row}")

# 'row' is broadcast to all 3 rows of 'matrix'
print(f"\nMatrix + Row:\n {matrix + row}")

print('-------------------------')

# Example 3: 2D array (3x3) and 1D *column*
# We need to make the column have shape (3, 1)
col = np.array([10, 20, 30])
print(f"\nColumn (3,):\n {col}")
print(f"!!! Error! (3,3) + (3,) doesn't work this way.")
# print(matrix + col) # This would broadcast like the row!

# We must reshape 'col' to be (3, 1)
col = col.reshape(3, 1)
# col = col[:, np.newaxis] # A common shortcut
print(f"\nReshaped Column (3,1):\n {col}")

# Now 'col' is broadcast to all 3 columns
print(f"\nMatrix + Column:\n {matrix + col}")

Array: [0 1 2 3 4]
Array + 10: [10 11 12 13 14]
-------------------------

Matrix (3x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Row (3,):
 [1 2 3]

Matrix + Row:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
-------------------------

Column (3,):
 [10 20 30]
!!! Error! (3,3) + (3,) doesn't work this way.

Reshaped Column (3,1):
 [[10]
 [20]
 [30]]

Matrix + Column:
 [[11. 11. 11.]
 [21. 21. 21.]
 [31. 31. 31.]]
