1D Array

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print('Dimensions : ',arr.ndim)
print('Shape : ',arr.shape)
print('Size : ',arr.size)


[1 2 3 4 5 6 7 8 9]
Dimensions :  1
Shape :  (9,)
Size :  9


2D Array

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print('Dimensions : ',arr.ndim)
print('Shape : ',arr.shape)
print('Size : ',arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions :  2
Shape :  (3, 3)
Size :  9


Numpy Functions

In [7]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [9]:
arr=np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
arr=np.arange(2,11,3)
print(arr)

[2 5 8]


In [18]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random Array Generator

In [20]:
arr=np.random.randint(1,10,(2,2))
print(arr)

[[4 6]
 [2 3]]


In [22]:
arr=np.random.rand(2,2)
print(arr)

[[0.0731818  0.47833928]
 [0.5436339  0.6398811 ]]


In [23]:
arr=np.random.randn(2,2)
print(arr)

[[ 0.02663986  0.90717912]
 [-0.88051125  0.40712456]]


In [24]:
arr=np.random.random((3,2))
print(arr)

[[0.0897671  0.51772048]
 [0.00552997 0.58752556]
 [0.86881513 0.96964903]]


Indexing and sliding

In [28]:
arr = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(arr[1][1])
print(arr[2][2])
print(arr[1,:])
print(arr[:,0])



22
33
[21 22 23]
[11 21 31]


In [33]:
arr=np.array([5,10,15,20,25,30,35,40])
print(arr)
print(arr[arr>20])
print(arr[arr % 5 == 0])
print(arr[arr % 2 == 0])

[ 5 10 15 20 25 30 35 40]
[25 30 35 40]
[ 5 10 15 20 25 30 35 40]
[10 20 30 40]


In [46]:
arr = np.array([
 [1,2,3,4],
 [5,6,7,8],
 [9,10,11,12]
])

print(arr)
print(arr[0:2,2:])
print(arr[:,1])
print(arr[2,::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
[ 2  6 10]
[ 9 11]
