1D Array

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print('Dimensions : ',arr.ndim)
print('Shape : ',arr.shape)
print('Size : ',arr.size)


[1 2 3 4 5 6 7 8 9]
Dimensions :  1
Shape :  (9,)
Size :  9


2D Array

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print('Dimensions : ',arr.ndim)
print('Shape : ',arr.shape)
print('Size : ',arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions :  2
Shape :  (3, 3)
Size :  9


Numpy Functions

In [6]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [8]:
arr=np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [9]:
arr=np.arange(2,11,3)
print(arr)

[2 5 8]


In [10]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random Array Generator

In [12]:
arr=np.random.randint(1,10,(2,2))
print(arr)

[[5 9]
 [9 7]]


In [13]:
arr=np.random.rand(2,2)
print(arr)

[[0.85114233 0.82814213]
 [0.8824512  0.38213264]]


In [14]:
arr=np.random.randn(2,2)
print(arr)

[[-0.69553749  0.11397761]
 [ 1.83141396  1.07002001]]


In [15]:
arr=np.random.random((3,2))
print(arr)

[[0.38597234 0.81532306]
 [0.90644088 0.86043965]
 [0.13019974 0.16339656]]


Indexing and sliding

In [16]:
arr = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(arr[1][1])
print(arr[2][2])
print(arr[1,:])
print(arr[:,0])



22
33
[21 22 23]
[11 21 31]


In [17]:
arr=np.array([5,10,15,20,25,30,35,40])
print(arr)
print(arr[arr>20])
print(arr[arr % 5 == 0])
print(arr[arr % 2 == 0])

[ 5 10 15 20 25 30 35 40]
[25 30 35 40]
[ 5 10 15 20 25 30 35 40]
[10 20 30 40]


In [18]:
arr = np.array([
 [1,2,3,4],
 [5,6,7,8],
 [9,10,11,12]
])

print(arr)
print(arr[0:2,2:])
print(arr[:,1])
print(arr[2,::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
[ 2  6 10]
[ 9 11]


Element-wise Arithmetic Operations

In [19]:

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


Array + Scalar Operations

In [20]:
a = np.array([10, 20, 30])

print(a + 5)
print(a * 2)
print(a / 10)


[15 25 35]
[20 40 60]
[1. 2. 3.]


Universal Functions (ufuncs)

In [21]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


Aggregate Functions

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.var())


21
3.5
6
1
1.707825127659933
2.9166666666666665


Axis Concept

In [23]:
arr = np.array([
 [1,2,3],
 [4,5,6]
])

print(arr.sum(axis=0))
print(arr.sum(axis=1))


[5 7 9]
[ 6 15]


Comparison

In [24]:
arr = np.array([10,20,30,40])

print(arr > 20)
print(arr == 20)
print(arr != 30)


[False False  True  True]
[False  True False False]
[ True  True False  True]


Broadcasting

In [25]:
arr = np.array([1,2,3])
print(arr + 5)


[6 7 8]


In [26]:
arr = np.array([
 [1,2,3],
 [4,5,6]
])

b = np.array([10,20,30])

print(arr + b)


[[11 22 33]
 [14 25 36]]


Tasks

In [27]:
a = np.array([5,10,15])
b = np.array([1,2,3])

print(a+b)
print(a*b)
print(a**2)
print(np.sqrt(b))

[ 6 12 18]
[ 5 20 45]
[ 25 100 225]
[1.         1.41421356 1.73205081]


In [28]:
m = np.array([
 [2,4,6],
 [3,6,9],
 [4,8,12]
])

print(m.sum(axis=1))
print(m.sum(axis=0))
print(m.mean())
print(m.std())

[12 18 24]
[ 9 18 27]
6.0
3.018461712712472


In [29]:
arr = np.array([
 [1,2,3],
 [4,5,6]
])
v = np.array([1,0,1])

print(arr+v)

[[2 2 4]
 [5 5 7]]


Reshaping Arrays

In [30]:

arr = np.arange(1, 13)  
print(arr.shape)  

arr2 = arr.reshape(3, 4)
print(arr2)
print(arr2.shape)


(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


Flattening Arrays

In [31]:

arr2 = np.array([[1,2,3],[4,5,6]])
flat = arr2.flatten()

print("Original array:")
print(arr2)
print("Flattened array:")
print(flat)

flat[0] = 100
print(arr2)  # still [[1 2 3],[4 5 6]]


Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [32]:

r = arr2.ravel()
print("Raveled array:", r)

r[0] = 100
print("Original array after modifying raveled array:")
print(arr2)


Raveled array: [1 2 3 4 5 6]
Original array after modifying raveled array:
[[100   2   3]
 [  4   5   6]]


Transpose

In [33]:
print(arr2.T)

[[100   4]
 [  2   5]
 [  3   6]]


Stacking Arrays

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))

print(np.vstack((a,b)))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Splitting Arrays

In [35]:
arr = np.arange(10)
np.split(arr, 2)  # split into 2 equal parts


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [36]:
arr2 = np.arange(16).reshape(4,4)
np.vsplit(arr2, 2)  # split rows


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Tasks

In [45]:
arr=np.arange(1,13)
print(arr)
ar=arr.reshape(3,4)
print(ar)
flaten=ar.flatten()
print(flaten)
print(ar.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a,'\n',b)
horzontal=np.hstack((a,b))

print("Horizonatal : ",horzontal)

Vertical=np.vstack((a,b))
print("Vertical :\n",Vertical)

[1 2 3] 
 [4 5 6]
Horizonatal :  [1 2 3 4 5 6]
Vertical :
 [[1 2 3]
 [4 5 6]]


In [56]:
arr=np.arange(0,10)
print(arr)

split_array=np.split(arr,5)
print(split_array)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [64]:
arr=np.arange(0,16).reshape(4,4)
print(arr)

left,right=np.hsplit(arr,2)
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
